services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    #networks:
      #- forex
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  coinbase-feeder:
    image: coinbase-feeder
    container_name: coinbase-feeder
    build:
      context: .
    depends_on:
      redis:
        condition: service_healthy
    #networks:
      #- forex
    #volumes:
      #- "~/.aws:/home/.aws"
    environment:
      - REDIS_HOST=redis
      - DEBUG=y


#networks:
  #forex: {}